[package]
name = "rocketscience"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
coord_2d = "0.3.3"
dialoguer = "0.10.0"
